import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* URL 파라미터 유실을 방지하기 위해 window.location.href 전체를 안전하게 인코딩합니다 */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var userAgent = navigator.userAgent.toLowerCase();
                if (userAgent.indexOf('kakaotalk') > -1) {
                  var currentUrl = window.location.href;
                  
                  if (userAgent.indexOf('iphone') > -1 || userAgent.indexOf('ipad') > -1 || userAgent.indexOf('ipod') > -1) {
                    // 아이폰 탈출
                    window.location.href = 'kakaotalk://web/openExternalApp?url=' + encodeURIComponent(currentUrl);
                  } else {
                    // 안드로이드 탈출 (파라미터가 깨지지 않도록 전체 url을 변환 없이 인텐트에 주입)
                    var cleanUrl = currentUrl.replace(/^https?:\\/\\//, '');
                    window.location.href = 'intent://' + cleanUrl + '#Intent;scheme=https;package=com.android.chrome;end';
                  }
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
