import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 오류를 일으키던 역슬래시를 없애고 안전하게 가공한 스크립트입니다 */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                var userAgent = navigator.userAgent.toLowerCase();
                if (userAgent.indexOf('kakaotalk') > -1) {
                  var currentUrl = window.location.href;
                  if (userAgent.indexOf('iphone') > -1 || userAgent.indexOf('ipad') > -1 || userAgent.indexOf('ipod') > -1) {
                    window.location.href = 'kakaotalk://web/openExternalApp?url=' + encodeURIComponent(currentUrl);
                  } else {
                    var rawUrl = currentUrl.replace('https://', '').replace('http://', '');
                    window.location.href = 'intent://' + rawUrl + '#Intent;scheme=https;package=com.android.chrome;end';
                  }
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
